### ISSUE TITLE
SQL error in install tool

### ISSUE THREAD

**Issue by fritzmg** [contao/installation-bundle#17]
After installing Contao `4.2.0` with

```
composer create-project contao/standard-edition <target> 4.2.0
```

and then opening the Install Tool with `/web/install.php`, I get the following SQL error:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c42dev.tl_cron' doesn't exist' in C:\xampp\htdocs\c42dev\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:57 Stack trace: #0 C:\xampp\htdocs\c42dev\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(57): PDO->exec('LOCK TABLES `tl...')
#1 C:\xampp\htdocs\c42dev\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1025): Doctrine\DBAL\Driver\PDOConnection->exec('LOCK TABLES `tl...')
#2 C:\xampp\htdocs\c42dev\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Database.php(644): Doctrine\DBAL\Connection->exec('LOCK TABLES `tl...')
#3 C:\xampp\htdocs\c42dev\vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendCron.php(140): Contao\Database->lockTables(Array)
#4 C:\xampp\htdocs\c42dev\vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendCron.php(54): Contao\FrontendCron->hasToWait()
#5 C:\xampp\htdocs\c42dev\vendor\contao\core-bundle\src\Even in C:\xampp\htdocs\c42dev\app\bootstrap.php.cache on line 2991
```

Someone else encountered the same issue here: https://community.contao.org/de/showthread.php?60137-Installations-Fehler&p=411922&viewfull=1#post411922

**Comment by fritzmg** [comment]
There is no entry in `/app/logs/prod.log` btw. (since this is from Contao's Kernel and not via Symfony's Kernel, I assume).

**Comment by leofeyer** [comment]
The `kernel.terminate` event triggers the `contao.listener.command_scheduler` listener, which then tries to run the cron jobs. Of course this fails if the table is not yet available.

**Comment by ghost** [comment]
The issue has been moved to contao/core-bundle#541.
